apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: deploy1
spec:
  replicas: 3 # Deployment 會建立/維護多個副本（replicas），，並確保 label 一致
  selector:
    matchLabels:
      app: deploy1 # 告訴 Deployment 要管理哪些 Pod
  template: # 一個 pod 的設定
    metadata:
      name: deploy1
      labels:
        app: deploy1 # Service deploy1-svc 靠這個撈 Pod
    spec:
      containers:
        - name: k8s-demo-app
          image: fy20047/k8s-demo-app:latest
          env:
            - name: MESSAGE
              value: "Hello from deploy1."
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm1
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret1
                  key: PASSWORD
          ports:
            - containerPort: 80
