apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: k8s.test.com # 先比對 Host
      http:
        paths:
          - path: /po1 # 再比對 Path
            pathType: Prefix
            backend:
              service: # 告訴 Ingress 下一跳要找哪個 Service
                name: po1-svc
                port:
                  number: 80
          - path: /deploy1
            pathType: Prefix
            backend:
              service:
                name: deploy1-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: popo-svc
                port:
                  number: 80
